# Generated by Django 4.1.3 on 2023-07-31 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="modelos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=45, verbose_name="TITULO")),
                (
                    "descripcion",
                    models.TextField(max_length=2000, verbose_name="DESCRIPCION"),
                ),
                ("imagen", models.ImageField(upload_to=True, verbose_name="IMAGEN")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="CREADO"),
                ),
                (
                    "upload",
                    models.DateTimeField(auto_now=True, verbose_name="REVISIÓN"),
                ),
            ],
            options={"verbose_name": "Modelo", "verbose_name_plural": "Modelos",},
        ),
    ]
