# Generated by Django 4.1.3 on 2023-08-06 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_2", "0002_modelos_published"),
    ]

    operations = [
        migrations.RemoveField(model_name="modelos", name="published",),
    ]
