# Generated by Django 4.1.3 on 2023-08-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_2", "0003_remove_modelos_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelos",
            name="url",
            field=models.URLField(default=2, max_length=2000, verbose_name="URL"),
            preserve_default=False,
        ),
    ]
