# Generated by Django 4.1.3 on 2023-08-07 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_2", "0004_modelos_url"),
    ]

    operations = [
        migrations.RemoveField(model_name="modelos", name="url",),
    ]
