# Generated by Django 4.1.3 on 2023-08-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_2", "0007_rename_upload_modelos_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelos",
            name="url_git",
            field=models.URLField(default=1, verbose_name="url"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="modelos",
            name="imagen",
            field=models.ImageField(upload_to="proyectos", verbose_name="IMAGEN"),
        ),
    ]
