# Generated by Django 4.1.3 on 2023-08-13 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_2", "0009_alter_modelos_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="modelos",
            options={"verbose_name": "Modelo", "verbose_name_plural": "Modelos"},
        ),
    ]
