# Generated by Django 4.1.3 on 2023-08-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="sobre_mi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=45, verbose_name="TITULO")),
                (
                    "descripcion",
                    models.TextField(max_length=2000, verbose_name="DESCRIPCION"),
                ),
                ("imagen", models.ImageField(upload_to=True, verbose_name="IMAGEN")),
            ],
            options={"verbose_name": "sobre_mi", "verbose_name_plural": "sobre_mis",},
        ),
    ]
